### PR TITLE
Updates to min versions

### PR DESCRIPTION
**Pull request by Sam-Burns**
Updating to reflect results of testing with `composer update --prefer-lowest`

### CODE REVIEW

**Comment by jeremeamia** [comment]
@grahamcampbell, could you please review. I haven't used `"conflict"` before.

**Comment by GrahamCampbell** [comment]
This looks incorrect to me.

**Comment by GrahamCampbell** [comment]
This just causes composer to resolve the version just before the conflict stuff was added.

**Comment by mnapoli** [comment]
+1 `conflict` is not needed here, versions constraints are already doing the job.

**Comment by GrahamCampbell** [comment]
> +1 conflict is not needed here, versions constraints are already doing the job.

ie :-1:

It's a :-1: from me too. ;)

**Comment by GrahamCampbell** [comment]
> Updating to reflect results of testing with composer update --prefer-lowest

If you need to do that, then the version constraints are wrong, and need increasing.

**Comment by Sam-Burns** [comment]
@GrahamCampbell completely with you on the need to increase the version constraints, as the PR does.  I see your point as well about the fact version 1.0 can still be installed, even if subsequent versions contain a `conflict` clause.

@mnapoli I'm not sure the version constraints are doing the job, to be honest.  With the version constraints appearing in the `require-dev` section of the `composer.json` file, they don't achieve anything for a user including this library as a dependency.  The real issue is whether it's best to express incompatibility between this library and, for example, Symfony 2.0, through the `conflict` clause.

With version 1.0.0 of Acclimate in the wild already, that ship may have sailed.  However, by adding a `conflict` section, we can at least offer users relying on Acclimate ^1.1, ^2.0 or whatever explicit conflict with Symfony 2.0.  The question I was asking myself when writing this PR is whether it's right to prevent a user from installing a future version of Acclimate, and a version of Symfony Service Container it can't wrap, at the same time.  We must be mindful of the fact that a user might conceivably be using the two libraries for two different things.

In some ways, it seems that some of the complexity would go away if the containers were in the `require` section of the `composer.json` file, but that seems a little out of scope for what we're trying to do here.

On balance, I think @GrahamCampbell has talked me out of this PR, and I will close it in favour of https://github.com/jeremeamia/acclimate-container/pull/36 .

**Pull request closed without merging**
