### PR TITLE
Running php-cs-fixer fix

### PR DESCRIPTION
**Pull request by Sam-Burns**
Ran `php-cs-fixer fix src/ --level=psr2` and `php-cs-fixer fix tests/ --level=psr2`.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Maybe setup https://styleci.io/?

**Comment by Sam-Burns** [comment]
@GrahamCampbell that's a good idea, I'll look into it.  Maybe with Scrutinizer checks already running, we should be able to spot any issues in future PRs though?  I'll find out more about what styleci can offer.

**Comment by GrahamCampbell** [comment]
StyleCI can offer full automation for CS fixing including sending and merging PRs both at request, or, automatically on push.

It's good to separate this from scrutinzier so StyleCI can focus on the cs, travis on the tests, and scrutinizer on the static analysis and code inspection. I find that scrutinizer does a poor job of dealing with cs.

---

NB I'm maybe biased because I'm lead dev for StyleCI.

**Comment by GrahamCampbell** [comment]
StyleCI is particularly good when it comes to merging external PRs with cs issues. If you've got auto sending/merging turned on, after you merge a PR, StyleCI can merge the fixes straight after. This means contributors don't need to worry about cs anymore, and people can focus on the code, not the cs. This is very useful in Laravel for example.

**Comment by shrikeh** [comment]
@Sam-Burns would you like a hand with this?

**Pull request merged**
