### PR TITLE
Bumping PHPUnit version

### PR DESCRIPTION
**Pull request by Sam-Burns**

### CODE REVIEW

**Comment by jeremeamia** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by GrahamCampbell** [comment]
Dependencies without an upper bound are always a bad idea.

**Comment by GrahamCampbell** [comment]
`~4.8|~5.0` might do just fine here.

**Comment by jeremeamia** [comment]
True, `|` and  `||` are generally better than using `<` and  `>`, when possible.

@Sam-Burns FYI: @GrahamCampbell is a `composer.json` wizard. I'd trust his opinion. He's never been wrong so far. He always swoops in and whips my `composer.json`s into shape. For Guzzle, AWS SDK, SuperClosure, etc.

**Comment by mnapoli** [comment]
If this is a dev dependency it might as well be `~5.0`?

**Comment by GrahamCampbell** [comment]
> If this is a dev dependency it might as well be ~5.0?

Not possible because phpunit 5 doesn't support php 5.4 or 5.5.

**Comment by mnapoli** [comment]
Then `~4.0`, my point is allowing 2 versions doesn't make sense.

**Comment by GrahamCampbell** [comment]
> Then ~4.0, my point is allowing 2 versions doesn't make sense.

It's absolutely required, PHPUnit 4 doesn't support PHP 7. It's a bug that composer allows it to be installed.

**Comment by GrahamCampbell** [comment]
I permanent bug because it's too late for phpunit to fix it.

**Comment by mnapoli** [comment]
Interesting, first time I hear of that! I've never seen that issue with PHPUnit, it seems it's isn't here either (the build is green on Travis on PHP 7) but I guess why not.

**Comment by Sam-Burns** [comment]
@jeremeamia Thanks for the background/introduction.  @GrahamCampbell thoughts on the PR in its current state?

**Pull request closed without merging**
